#!/bin/bash
# ============================================================
#  VoidPanel — Server-Side Release Deployment (NO GIT)
#  Run on the voidpanel.com server AFTER files are uploaded.
#
#  Usage:
#    bash deploy.sh 2.2.0
#    bash deploy.sh 2.2.0 "Fixed update endpoint and reseller login"
# ============================================================
set -euo pipefail

VERSION="${1:-}"
NOTES="${2:-VoidPanel v$VERSION}"
DEPLOY_DIR="/var/www/voidpanel.com/deploy"
DJANGO_DIR="/var/www/voidpanel.com"
VENV="$DJANGO_DIR/venv/bin/activate"

if [ -z "$VERSION" ]; then
    echo "❌ Usage: bash deploy.sh <VERSION> [\"Release notes\"]"
    exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  VoidPanel Deploy — v$VERSION               "
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── Step 1: Run Django migrations on the website itself ────
echo "🗄️  Running website migrations ..."
cd "$DJANGO_DIR"
source "$VENV" 2>/dev/null || true
python manage.py migrate --noinput
python manage.py collectstatic --noinput
echo "   ✅ Website migrations done"

# ── Step 1b: Seed default data + validate config ────────────
echo ""
echo "⚙️  Running post-deploy setup (email plans, server check, Razorpay) ..."
python manage.py setup_defaults
echo "   ✅ Setup defaults done"

# ── Step 2: Create per-version update script ───────────────
SCRIPT_DIR="$DJANGO_DIR/static/updates/$VERSION"
mkdir -p "$SCRIPT_DIR"

echo ""
echo "📝 Creating update script at /updates/$VERSION/update.sh ..."
cat > "$SCRIPT_DIR/update.sh" << SCRIPT
#!/bin/bash
# VoidPanel Update Script — v${VERSION}
# Auto-generated by deploy.sh on $(date)
set -euo pipefail

VERSION="${VERSION}"
PANEL_DIR="/var/www/panel"
VERSION_FILE="/etc/version.txt"
RELEASE_URL="https://voidpanel.com/releases/voidpanel-\${VERSION}.tar.gz"
BACKUP_DIR="/var/backups/voidpanel-pre-\${VERSION}-\$(date +%Y%m%d%H%M%S)"
LOG_FILE="/var/log/voidpanel/update-\${VERSION}.log"

log() { echo "[\$(date '+%Y-%m-%d %H:%M:%S')] \$1" | tee -a "\$LOG_FILE"; }
mkdir -p "\$(dirname "\$LOG_FILE")"
log "=== VoidPanel Update to v\${VERSION} ==="

# Backup
log "Backing up to \$BACKUP_DIR ..."
cp -r "\$PANEL_DIR" "\$BACKUP_DIR" 2>/dev/null || true

# Download tarball from voidpanel.com
log "Downloading release tarball ..."
TMP=\$(mktemp -d)
curl -fsSL "\$RELEASE_URL" -o "\$TMP/release.tar.gz"
tar -xzf "\$TMP/release.tar.gz" -C "\$TMP"
EXTRACTED=\$(find "\$TMP" -mindepth 1 -maxdepth 1 -type d | head -1)

# Preserve settings and .env
cp "\$PANEL_DIR/panel/settings.py" "\$TMP/settings.bak" 2>/dev/null || true
cp "\$PANEL_DIR/.env"              "\$TMP/env.bak"       2>/dev/null || true

# Apply files
log "Applying files ..."
rsync -a --exclude='*.pyc' --exclude='__pycache__' \\
      --exclude='db.sqlite3' --exclude='media/' --exclude='.env' \\
      "\$EXTRACTED/" "\$PANEL_DIR/"

# Restore settings and .env
cp "\$TMP/settings.bak" "\$PANEL_DIR/panel/settings.py" 2>/dev/null || true
cp "\$TMP/env.bak"      "\$PANEL_DIR/.env"              2>/dev/null || true

# Install deps and migrate
log "Installing dependencies ..."
cd "\$PANEL_DIR"
source venv/bin/activate 2>/dev/null || true
pip install -r requirements.txt -q
python manage.py migrate --noinput
python manage.py collectstatic --noinput

# Update version file
echo "\$VERSION" > "\$VERSION_FILE"
log "Version updated to \$VERSION."

# Restart panel
log "Restarting panel service ..."
systemctl restart voidpanel 2>/dev/null || \\
  (pkill -f "gunicorn.*panel" 2>/dev/null; sleep 2; \\
   cd "\$PANEL_DIR" && source venv/bin/activate && \\
   gunicorn panel.wsgi:application --bind 0.0.0.0:8080 --workers 3 --daemon)

rm -rf "\$TMP"
log "=== v\${VERSION} complete! ==="
SCRIPT

chmod +x "$SCRIPT_DIR/update.sh"
echo "   ✅ Update script created"

# ── Step 3: Create release tarball from uploaded code ──────
echo ""
echo "📦 Creating release tarball: voidpanel-${VERSION}.tar.gz ..."
mkdir -p "$DJANGO_DIR/media/releases"
tar -czf "$DJANGO_DIR/media/releases/voidpanel-${VERSION}.tar.gz" \
    -C "$DJANGO_DIR" \
    --exclude='*.pyc' \
    --exclude='__pycache__' \
    --exclude='*.sqlite3' \
    --exclude='media' \
    --exclude='.env' \
    --exclude='venv' \
    --exclude='.venv' \
    --exclude='deploy' \
    --exclude='staticfiles' \
    --transform "s,^\.,voidpanel-${VERSION}," \
    .
echo "   ✅ Tarball: /media/releases/voidpanel-${VERSION}.tar.gz"

# ── Step 4: Register version in Django database ────────────
echo ""
echo "🗄️  Registering v${VERSION} in database ..."
source "$VENV" 2>/dev/null || true
python manage.py shell -c "
from data.models import updates
obj, created = updates.objects.update_or_create(
    version='${VERSION}',
    defaults={
        'notes':       '''${NOTES}''',
        'script_url':  'https://voidpanel.com/updates/${VERSION}/update.sh',
        'is_active':   True,
        'is_breaking': False,
    }
)
action = 'Created' if created else 'Updated'
print(f'  {action} v${VERSION} in database')
"
echo "   ✅ Database registered"

# ── Step 5: Reload nginx ────────────────────────────────────
echo ""
echo "🔄 Reloading nginx ..."
nginx -t && systemctl reload nginx
echo "   ✅ Nginx reloaded"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅ v$VERSION deployed to voidpanel.com!"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Tarball : https://voidpanel.com/releases/voidpanel-$VERSION.tar.gz"
echo "║  Script  : https://voidpanel.com/updates/$VERSION/update.sh"
echo "║  API     : https://voidpanel.com/version_name/"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  All servers will see the update on next check."
echo "  To push immediately → Super Admin → Update Manager → Push All"
echo ""
