#!/bin/bash
# VoidPanel Update Script — v2.5.23
# Auto-generated by deploy.sh on Thu Jul  2 05:57:09 PM CEST 2026
set -euo pipefail

VERSION="2.5.23"
PANEL_DIR="/var/www/panel"
VERSION_FILE="/etc/version.txt"
RELEASE_URL="https://voidpanel.com/releases/voidpanel-${VERSION}.tar.gz"
BACKUP_DIR="/var/backups/voidpanel-pre-${VERSION}-$(date +%Y%m%d%H%M%S)"
LOG_FILE="/var/log/voidpanel/update-${VERSION}.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"; }
mkdir -p "$(dirname "$LOG_FILE")"
log "=== VoidPanel Update to v${VERSION} ==="

# Backup
log "Backing up to $BACKUP_DIR ..."
cp -r "$PANEL_DIR" "$BACKUP_DIR" 2>/dev/null || true

# Download tarball from voidpanel.com
log "Downloading release tarball ..."
TMP=$(mktemp -d)
curl -fsSL "$RELEASE_URL" -o "$TMP/release.tar.gz"
tar -xzf "$TMP/release.tar.gz" -C "$TMP"
EXTRACTED=$(find "$TMP" -mindepth 1 -maxdepth 1 -type d | head -1)

# Preserve settings and .env
cp "$PANEL_DIR/panel/settings.py" "$TMP/settings.bak" 2>/dev/null || true
cp "$PANEL_DIR/.env"              "$TMP/env.bak"       2>/dev/null || true

# Apply files
log "Applying files ..."
rsync -a --exclude='*.pyc' --exclude='__pycache__' \
      --exclude='db.sqlite3' --exclude='media/' --exclude='.env' \
      "$EXTRACTED/" "$PANEL_DIR/"

# Restore settings and .env
cp "$TMP/settings.bak" "$PANEL_DIR/panel/settings.py" 2>/dev/null || true
cp "$TMP/env.bak"      "$PANEL_DIR/.env"              2>/dev/null || true

# Install deps and migrate
log "Installing dependencies ..."
cd "$PANEL_DIR"
source venv/bin/activate 2>/dev/null || true
pip install -r requirements.txt -q
python manage.py migrate --noinput
python manage.py collectstatic --noinput

# Setup phpMyAdmin SSO if installed
if [ -d "/usr/share/phpmyadmin" ]; then
    log "Configuring phpMyAdmin SSO gateway ..."
    cat > /usr/share/phpmyadmin/vp_sso.php << 'PMASSOEOF'
<?php
session_name('phpMyAdmin');
session_start();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); die('Method not allowed.'); }
$user     = isset($_POST['temp_user'])     ? trim($_POST['temp_user'])     : '';
$password = isset($_POST['temp_password']) ? trim($_POST['temp_password']) : '';
if (empty($user) || empty($password)) { http_response_code(400); die('Missing credentials.'); }
if (!preg_match('/^vp_temp_[a-z0-9]+$/', $user)) { http_response_code(403); die('Forbidden.'); }
$_SESSION['PMA_single_signon_user']     = $user;
$_SESSION['PMA_single_signon_password'] = $password;
$_SESSION['PMA_single_signon_host']     = 'localhost';
$_SESSION['PMA_single_signon_port']     = '3306';
session_write_close();
header('Location: index.php');
exit;
PMASSOEOF

    chown www-data:www-data /usr/share/phpmyadmin/vp_sso.php 2>/dev/null || true
    chmod 644 /usr/share/phpmyadmin/vp_sso.php 2>/dev/null || true

    for PMA_CONF in "/etc/phpmyadmin/config.inc.php" "/usr/share/phpmyadmin/config.inc.php"; do
        if [[ -f "$PMA_CONF" ]]; then
            if ! grep -q "PMA_single_signon" "$PMA_CONF" 2>/dev/null; then
                cat >> "$PMA_CONF" << 'PMACONF'
$cfg['Servers'][1]['auth_type']       = 'signon';
$cfg['Servers'][1]['SignonSession']   = 'phpMyAdmin';
$cfg['Servers'][1]['SignonURL']       = '/vp_sso.php';
$cfg['Servers'][1]['LogoutURL']       = '/vp_sso.php';
PMACONF
            fi
        fi
    done
fi

# Update version file — write to both locations
# /etc/version.txt  — read by panel on production
# panel/version.txt — fallback used in dev / if /etc is read-only
echo "$VERSION" | tee /etc/version.txt > /dev/null 2>&1 || true
echo "$VERSION" > "$PANEL_DIR/version.txt" 2>/dev/null || true
chown www-data:www-data /etc/version.txt "$PANEL_DIR/version.txt" 2>/dev/null || true
log "Version updated to $VERSION."

# Restart panel
log "Restarting panel service ..."
systemctl restart voidpanel voidpanel-daphne voidpanel-celery 2>/dev/null || \
  (pkill -f "gunicorn.*panel" 2>/dev/null; sleep 2; \
   cd "$PANEL_DIR" && source venv/bin/activate && \
   gunicorn panel.wsgi:application --bind 0.0.0.0:8080 --workers 3 --daemon)

rm -rf "$TMP"
log "=== v${VERSION} complete! ==="
