import pexpect
child = pexpect.spawn('ssh -o StrictHostKeyChecking=no root@178.18.250.134', timeout=60, encoding='utf-8')
child.expect('password:')
child.sendline('19072002ROHANkumar')
child.expect('# ')
child.sendline('cat << "PYCODE" > /tmp/test_eval.py\nimport os, sys\nsys.path.append("/var/www/panel/website/voidpanel")\nos.environ.setdefault("DJANGO_SETTINGS_MODULE", "voidpanel.settings")\nimport django; django.setup()\nfrom voidplatform.linux.web import get_active_engine_manager\nimport re\nmgr = get_active_engine_manager()\nconf = mgr.read_site_config("namanitwork.tech")\nhas_cache = "# VP_NGINX_CACHE_START" in conf\nprint("Before:", has_cache)\nnew_conf = re.sub(r"\\s*# VP_NGINX_CACHE_START.*?# VP_NGINX_CACHE_END", "", conf, flags=re.DOTALL)\nres = mgr.write_and_test_site_config("namanitwork.tech", new_conf)\nprint("Result.success:", res.success)\nconf_check = mgr.read_site_config("namanitwork.tech")\nprint("After:", "# VP_NGINX_CACHE_START" in conf_check)\nPYCODE')
child.expect('# ')
child.sendline("python3 /tmp/test_eval.py")
child.expect('# ', timeout=30)
print(child.before.strip())
child.sendline('exit')
