"""Abstract base classes for VoidPanel platform operations.

Every method here must be implemented by both Linux and Windows backends.
Views and tasks call these methods instead of direct subprocess calls.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class CommandResult:
    """Result of a platform command execution."""
    success: bool
    output: str = ""
    error: str = ""
    return_code: int = 0


class ServiceManager(ABC):
    @abstractmethod
    def start(self, service: str) -> CommandResult: ...
    @abstractmethod
    def stop(self, service: str) -> CommandResult: ...
    @abstractmethod
    def restart(self, service: str) -> CommandResult: ...
    @abstractmethod
    def reload(self, service: str) -> CommandResult: ...
    @abstractmethod
    def enable(self, service: str) -> CommandResult: ...
    @abstractmethod
    def disable(self, service: str) -> CommandResult: ...
    @abstractmethod
    def is_active(self, service: str) -> bool: ...


class UserManager(ABC):
    @abstractmethod
    def create_user(self, username: str, password: str, shell: str = '',
                    home_dir: str = '') -> CommandResult: ...
    @abstractmethod
    def delete_user(self, username: str, remove_home: bool = True) -> CommandResult: ...
    @abstractmethod
    def change_password(self, username: str, password: str) -> CommandResult: ...
    @abstractmethod
    def set_quota(self, username: str, soft_limit: int, hard_limit: int,
                  inode_soft: int = 0, inode_hard: int = 0) -> CommandResult: ...
    @abstractmethod
    def user_exists(self, username: str) -> bool: ...


class WebServerManager(ABC):
    @abstractmethod
    def create_site(self, domain: str, root_dir: str,
                    php_version: str = '', ssl: bool = False) -> CommandResult: ...
    @abstractmethod
    def delete_site(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def enable_site(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def disable_site(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def test_config(self) -> CommandResult: ...
    @abstractmethod
    def reload(self) -> CommandResult: ...
    @abstractmethod
    def get_site_config_path(self, domain: str) -> str: ...
    @abstractmethod
    def read_site_config(self, domain: str) -> str: ...
    @abstractmethod
    def write_and_test_site_config(self, domain: str, config_text: str) -> CommandResult: ...
    @abstractmethod
    def setup_reverse_proxy(self, domain: str, app_name: str, proxy_type: str, target: str, static_path: str = '', root_path: str = '') -> CommandResult: ...
    @abstractmethod
    def remove_reverse_proxy(self, domain: str, app_name: str) -> CommandResult: ...


class DNSManager(ABC):
    @abstractmethod
    def create_zone(self, domain: str, ip: str, ns1: str = '', ns2: str = '') -> CommandResult: ...
    @abstractmethod
    def delete_zone(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def add_record(self, domain: str, record_type: str, name: str,
                   value: str, ttl: int = 3600) -> CommandResult: ...
    @abstractmethod
    def delete_record(self, domain: str, record_type: str, name: str) -> CommandResult: ...
    @abstractmethod
    def check_zone(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def reload(self) -> CommandResult: ...


class MailManager(ABC):
    @abstractmethod
    def create_domain(self, domain: str, username: str = '') -> CommandResult: ...
    @abstractmethod
    def delete_domain(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def create_account(self, email: str, password: str, username: str = '') -> CommandResult: ...
    @abstractmethod
    def delete_account(self, email: str) -> CommandResult: ...
    @abstractmethod
    def change_account_password(self, email: str, password: str) -> CommandResult: ...
    @abstractmethod
    def reload(self) -> CommandResult: ...


class FTPManager(ABC):
    @abstractmethod
    def add_user(self, username: str, password: str, home_dir: str) -> CommandResult: ...
    @abstractmethod
    def remove_user(self, username: str) -> CommandResult: ...
    @abstractmethod
    def change_password(self, username: str, password: str) -> CommandResult: ...
    @abstractmethod
    def reload(self) -> CommandResult: ...


class FirewallManager(ABC):
    @abstractmethod
    def allow_port(self, port: int, protocol: str = 'tcp') -> CommandResult: ...
    @abstractmethod
    def deny_port(self, port: int, protocol: str = 'tcp') -> CommandResult: ...
    @abstractmethod
    def allow_ip(self, ip: str) -> CommandResult: ...
    @abstractmethod
    def deny_ip(self, ip: str) -> CommandResult: ...
    @abstractmethod
    def reload(self) -> CommandResult: ...


class SSLManager(ABC):
    @abstractmethod
    def provision(self, domain: str, webroot: str = '', email: str = '') -> CommandResult: ...
    @abstractmethod
    def revoke(self, domain: str) -> CommandResult: ...
    @abstractmethod
    def get_cert_path(self, domain: str) -> str: ...
    @abstractmethod
    def get_key_path(self, domain: str) -> str: ...
    @abstractmethod
    def generate_self_signed(self, domain: str, cert_path: str, key_path: str) -> CommandResult: ...


class PHPManager(ABC):
    @abstractmethod
    def get_installed_versions(self) -> list: ...
    @abstractmethod
    def get_active_version(self, domain: str = '') -> str: ...
    @abstractmethod
    def switch_version(self, domain: str, version: str) -> CommandResult: ...
    @abstractmethod
    def get_modules(self, version: str) -> list: ...


class TerminalManager(ABC):
    @abstractmethod
    def is_available(self) -> bool: ...
    @abstractmethod
    def spawn_shell(self, user: str = '') -> tuple: ...
    @abstractmethod
    def read(self, fd, size: int = 8192) -> bytes: ...
    @abstractmethod
    def write(self, fd, data: bytes) -> None: ...
    @abstractmethod
    def resize(self, fd, rows: int, cols: int) -> None: ...
    @abstractmethod
    def kill(self, pid) -> None: ...


class Platform(ABC):
    """Top-level platform interface aggregating all managers."""
    @property
    @abstractmethod
    def services(self) -> ServiceManager: ...
    @property
    @abstractmethod
    def users(self) -> UserManager: ...
    @property
    @abstractmethod
    def web(self) -> WebServerManager: ...
    @property
    @abstractmethod
    def dns(self) -> DNSManager: ...
    @property
    @abstractmethod
    def mail(self) -> MailManager: ...
    @property
    @abstractmethod
    def ftp(self) -> FTPManager: ...
    @property
    @abstractmethod
    def firewall(self) -> FirewallManager: ...
    @property
    @abstractmethod
    def ssl(self) -> SSLManager: ...
    @property
    @abstractmethod
    def php(self) -> PHPManager: ...
    @property
    @abstractmethod
    def terminal(self) -> TerminalManager: ...
