# Generated by Django 5.1.2 on 2024-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromai', models.TextField(default='None')),
                ('toai', models.TextField(default='None')),
                ('user', models.CharField(default='None', max_length=60)),
                ('name', models.CharField(default='None', max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
