# Generated by Django 5.1.2 on 2024-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromai',
            field=models.TextField(default=None),
        ),
    ]
