# Generated by Django 5.1.2 on 2024-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_alter_message_fromai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromai',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='message',
            name='toai',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='None', max_length=60),
        ),
    ]
