# Generated by Django 6.0.4 on 2026-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_livechatmessage_livechatsession_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='livechatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
