# Generated by Django 5.2.1 on 2026-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_livechatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatsession',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='no_agent_notified',
            field=models.BooleanField(default=False),
        ),
    ]
