# Generated by Django 5.1.1 on 2024-10-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
