# Generated by Django 5.1.1 on 2024-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_installed'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.CharField(default=None, max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientdocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.CharField(default=None, max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
