# Generated by Django 5.1.1 on 2024-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_admindocumentation_clientdocumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=None, max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
