# Generated by Django 5.1.2 on 2024-11-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='negative_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.CharField(default=None, max_length=60)),
                ('category', models.CharField(default=None, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='positive_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.CharField(default=None, max_length=60)),
            ],
        ),
    ]
