# Generated by Django 5.1.2 on 2024-11-24 04:24

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_negative_review_positive_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='negative_review',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positive_review',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 11, 24, 4, 24, 59, 512351, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
