# Generated by Django 5.1.2 on 2024-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_negative_review_date_positive_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='negative_review',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='positive_review',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
