# Generated by Django 5.1.1 on 2026-04-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_hostingorder_ticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidPanelServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., US-East Node 1', max_length=120, unique=True)),
                ('url', models.URLField(help_text='e.g., http://178.18.250.134:8080')),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hostingpackage',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Assigned server node for provisioning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='data.voidpanelserver'),
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_services', to='data.voidpanelserver'),
        ),
    ]
