# Generated by Django 6.0.4 on 2026-04-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_connectresellerconfig_coupon_domainorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(blank=True, help_text='Razorpay Key ID (starts with rzp_test_ or rzp_live_)', max_length=80)),
                ('key_secret', models.CharField(blank=True, help_text='Razorpay Key Secret — stored encrypted', max_length=120)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret from Razorpay dashboard', max_length=120)),
                ('is_active', models.BooleanField(default=False, help_text='Enable Razorpay checkout on invoice payment page')),
                ('is_live_mode', models.BooleanField(default=False, help_text='False = Test mode, True = Live mode')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Razorpay Config',
                'verbose_name_plural': 'Razorpay Configs',
            },
        ),
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('amount_paise', models.PositiveIntegerField(help_text='Amount in paise (INR × 100)')),
                ('status', models.CharField(choices=[('created', 'Order Created'), ('captured', 'Payment Captured'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('error_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_payments', to='data.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razorpay Payment',
                'verbose_name_plural': 'Razorpay Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
