# Generated by Django 6.0.4 on 2026-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_razorpay_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpayconfig',
            name='key_id',
        ),
        migrations.RemoveField(
            model_name='razorpayconfig',
            name='key_secret',
        ),
        migrations.AddField(
            model_name='razorpayconfig',
            name='live_key_id',
            field=models.CharField(blank=True, help_text='Live Key ID — starts with rzp_live_', max_length=100),
        ),
        migrations.AddField(
            model_name='razorpayconfig',
            name='live_key_secret',
            field=models.CharField(blank=True, help_text='Live Key Secret — treat like a password', max_length=140),
        ),
        migrations.AddField(
            model_name='razorpayconfig',
            name='test_key_id',
            field=models.CharField(blank=True, help_text='Test Key ID — starts with rzp_test_', max_length=100),
        ),
        migrations.AddField(
            model_name='razorpayconfig',
            name='test_key_secret',
            field=models.CharField(blank=True, help_text='Test Key Secret', max_length=140),
        ),
        migrations.AlterField(
            model_name='razorpayconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Show Razorpay checkout on invoice pages'),
        ),
        migrations.AlterField(
            model_name='razorpayconfig',
            name='is_live_mode',
            field=models.BooleanField(default=False, help_text='False = Test mode  |  True = Live (real money)'),
        ),
        migrations.AlterField(
            model_name='razorpayconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Webhook signing secret from Razorpay dashboard', max_length=140),
        ),
    ]
