# Generated by Django 5.1.1 on 2026-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_razorpay_prod_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=180)),
                ('storage_gb', models.PositiveIntegerField(default=50)),
                ('max_accounts', models.PositiveIntegerField(default=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, help_text='Set to zero to auto-calculate from monthly', max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseller Package',
                'verbose_name_plural': 'Reseller Packages',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reseller Custom Pricing Rules', max_length=120)),
                ('base_price_monthly', models.DecimalField(decimal_places=2, default=15.0, help_text='Base price containing the infrastructure minimal cost + voidpanel access', max_digits=8)),
                ('base_storage_gb', models.PositiveIntegerField(default=10, help_text='Base storage included in base price')),
                ('base_accounts', models.PositiveIntegerField(default=5, help_text='Base accounts included in base price')),
                ('price_per_10gb_storage', models.DecimalField(decimal_places=2, default=1.5, max_digits=8)),
                ('price_per_5_accounts', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
                ('storage_min_gb', models.PositiveIntegerField(default=10)),
                ('storage_max_gb', models.PositiveIntegerField(default=1000)),
                ('accounts_min', models.PositiveIntegerField(default=5)),
                ('accounts_max', models.PositiveIntegerField(default=500)),
                ('yearly_discount_percent', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reseller Pricing Settings',
                'verbose_name_plural': 'Reseller Pricing Settings',
            },
        ),
    ]
