# Generated by Django 5.1.1 on 2026-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_resellerpackage_resellerpricingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Google Gemini API Key', max_length=255)),
                ('gemini_model', models.CharField(default='gemini-2.0-flash', max_length=80)),
                ('claude_api_key', models.CharField(blank=True, help_text='Anthropic Claude API Key', max_length=255)),
                ('claude_model', models.CharField(default='claude-3-5-sonnet-20241022', max_length=80)),
                ('openai_api_key', models.CharField(blank=True, help_text='OpenAI API Key', max_length=255)),
                ('openai_model', models.CharField(default='gpt-4o', max_length=80)),
                ('active_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI ChatGPT')], default='gemini', help_text='Which provider processes panel AI requests', max_length=20)),
                ('tokens_per_request', models.PositiveIntegerField(default=1, help_text='Tokens deducted per chat request')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Config',
            },
        ),
    ]
