# Generated by Django 6.0.4 on 2026-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_ai_provider_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingpackage',
            name='package_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('reseller', 'Reseller Hosting'), ('wordpress', 'WordPress Hosting')], default='shared', max_length=20),
        ),
    ]
