# Generated by Django 6.0.4 on 2026-04-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_hostingpackage_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerpackage',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Assigned server node for provisioning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_packages', to='data.voidpanelserver'),
        ),
        migrations.AddField(
            model_name='voidpanelserver',
            name='last_ping_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voidpanelserver',
            name='server_version',
            field=models.CharField(blank=True, help_text='VoidPanel version reported by this node', max_length=40),
        ),
    ]
