# Generated by Django 5.1.1 on 2026-04-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_resellerpackage_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSuspendSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master toggle — if False, NO automatic suspension will occur regardless of other settings.')),
                ('overdue_days', models.PositiveIntegerField(default=15, help_text='Days after invoice due date before the hosting service is automatically suspended.')),
                ('warning_days', models.PositiveIntegerField(default=10, help_text='Days after due date to send the customer a warning email before suspension.')),
                ('send_warning_email', models.BooleanField(default=True, help_text='Send an overdue warning email to the customer before suspension.')),
                ('send_suspension_email', models.BooleanField(default=True, help_text='Send a suspension notification email to the customer.')),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto-Suspend Settings',
                'verbose_name_plural': 'Auto-Suspend Settings',
            },
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='is_reseller',
            field=models.BooleanField(default=False, help_text='True when this is a Reseller Hosting service'),
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='panel_password',
            field=models.CharField(blank=True, help_text='Plain-text password shown once after provisioning', max_length=255),
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='panel_username',
            field=models.CharField(blank=True, help_text='System username on the VoidPanel server', max_length=150),
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='sso_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hostingservice',
            name='sso_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
