# Generated by Django 6.0.4 on 2026-04-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_ssl_plan_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, help_text='0 = auto-calculate from monthly * 10', max_digits=8)),
                ('max_accounts', models.PositiveIntegerField(default=3, help_text='Max connected social accounts. 0 = unlimited.')),
                ('max_scheduled_posts_per_month', models.PositiveIntegerField(default=30, help_text='Max posts scheduled per month. 0 = unlimited.')),
                ('max_ai_captions_per_month', models.PositiveIntegerField(default=0, help_text='Max AI caption generations per month. 0 = unlimited.')),
                ('max_team_members', models.PositiveIntegerField(default=1)),
                ('media_storage_gb', models.PositiveIntegerField(default=1, help_text='Media library storage in GB.')),
                ('allowed_platforms', models.JSONField(default=list, help_text='e.g. ["fb","ig","tw"] — empty = all platforms')),
                ('has_analytics', models.BooleanField(default=True)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_unified_inbox', models.BooleanField(default=False)),
                ('has_ai_captions', models.BooleanField(default=False)),
                ('has_csv_export', models.BooleanField(default=False)),
                ('has_calendar_view', models.BooleanField(default=True)),
                ('has_bulk_schedule', models.BooleanField(default=False)),
                ('has_link_shortener', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Media Plan',
                'verbose_name_plural': 'Social Media Plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.AlterField(
            model_name='emailmailbox',
            name='password',
            field=models.CharField(blank=True, help_text='Stored for portal display only', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailplan',
            name='max_mailboxes',
            field=models.PositiveIntegerField(default=5, help_text='Max mailboxes per customer domain'),
        ),
        migrations.AlterField(
            model_name='emailplan',
            name='server',
            field=models.ForeignKey(blank=True, help_text='VoidPanel server node where email accounts will be provisioned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_plans', to='data.voidpanelserver'),
        ),
        migrations.AlterField(
            model_name='emailplan',
            name='storage_per_mailbox_gb',
            field=models.PositiveIntegerField(default=5, help_text='Storage quota per mailbox (GB)'),
        ),
        migrations.AlterField(
            model_name='emailservice',
            name='domain',
            field=models.CharField(help_text='Customer domain, e.g. mycompany.com', max_length=120),
        ),
        migrations.AlterField(
            model_name='emailservice',
            name='panel_url',
            field=models.URLField(blank=True, help_text='Base URL of the panel server'),
        ),
        migrations.AlterField(
            model_name='emailservice',
            name='webmail_url',
            field=models.URLField(blank=True, help_text='Direct Roundcube webmail URL'),
        ),
        migrations.AlterField(
            model_name='sslplan',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Auto-renew certificate before expiry'),
        ),
        migrations.AlterField(
            model_name='sslplan',
            name='max_domains',
            field=models.PositiveIntegerField(default=1, help_text='Number of domains/SANs included'),
        ),
        migrations.AlterField(
            model_name='sslplan',
            name='server',
            field=models.ForeignKey(blank=True, help_text='VoidPanel server where certbot will issue certificates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_plans', to='data.voidpanelserver'),
        ),
        migrations.AlterField(
            model_name='sslplan',
            name='validity_days',
            field=models.PositiveIntegerField(default=90, help_text="Certificate validity in days (Let's Encrypt = 90)"),
        ),
        migrations.AlterField(
            model_name='sslservice',
            name='cert_path',
            field=models.CharField(blank=True, help_text='Path on server, e.g. /etc/letsencrypt/live/domain/', max_length=255),
        ),
        migrations.AlterField(
            model_name='sslservice',
            name='domain',
            field=models.CharField(help_text='Primary domain (e.g. example.com)', max_length=120),
        ),
        migrations.AlterField(
            model_name='sslservice',
            name='notes',
            field=models.TextField(blank=True, help_text='Error messages or admin notes'),
        ),
        migrations.AlterField(
            model_name='sslservice',
            name='san_domains',
            field=models.JSONField(blank=True, default=list, help_text='Additional SANs for multi-domain plans'),
        ),
        migrations.CreateModel(
            name='SocialMediaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('accounts_connected', models.PositiveIntegerField(default=0)),
                ('posts_scheduled_this_month', models.PositiveIntegerField(default=0)),
                ('ai_captions_used_this_month', models.PositiveIntegerField(default=0)),
                ('media_storage_used_mb', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='data.socialmediaplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Media Service',
                'verbose_name_plural': 'Social Media Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
