# Generated by Django 6.0.3 on 2026-04-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_social_media_plan_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, help_text='0 = auto-calculate from monthly * 10', max_digits=8)),
                ('max_leads', models.PositiveIntegerField(default=500, help_text='Max contacts/leads stored. 0 = unlimited.')),
                ('max_emails_per_month', models.PositiveIntegerField(default=1000, help_text='Max marketing emails sent per month. 0 = unlimited.')),
                ('max_ai_copies_per_month', models.PositiveIntegerField(default=10, help_text='Max AI marketing copies generated per month. 0 = unlimited.')),
                ('has_ab_testing', models.BooleanField(default=False)),
                ('has_whatsapp_automation', models.BooleanField(default=False)),
                ('has_omnichannel_campaigns', models.BooleanField(default=True)),
                ('has_lead_scoring', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketing Plan',
                'verbose_name_plural': 'Marketing Plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='MarketingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('leads_stored', models.PositiveIntegerField(default=0)),
                ('emails_sent_this_month', models.PositiveIntegerField(default=0)),
                ('ai_copies_used_this_month', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='data.marketingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Service',
                'verbose_name_plural': 'Marketing Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('form', 'Website Form'), ('import', 'CSV Import'), ('ad', 'Paid Ad'), ('organic', 'Organic')], default='manual', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=50, help_text='0-100 lead quality score')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='data.marketingservice')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('social', 'Social Media'), ('ad', 'Paid Ad')], default='email', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('open_rate', models.FloatField(default=0)),
                ('click_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='data.marketingservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variant_a', models.TextField()),
                ('variant_b', models.TextField()),
                ('metric', models.CharField(default='clicks', max_length=50)),
                ('winner', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('clicks_a', models.PositiveIntegerField(default=0)),
                ('clicks_b', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='data.marketingservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
