# Generated by Django 6.0.3 on 2026-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_marketingplan_marketingservice_marketinglead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerpackage',
            name='client_bandwidth_gb',
            field=models.PositiveIntegerField(default=50, help_text='Monthly bandwidth per client account (GB)'),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_databases',
            field=models.PositiveIntegerField(default=3, help_text='Max MySQL databases per client'),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_email_accounts',
            field=models.PositiveIntegerField(default=5, help_text='Max email accounts per client'),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_ftp_accounts',
            field=models.PositiveIntegerField(default=2, help_text='Max FTP accounts per client'),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_package_name',
            field=models.CharField(default='Starter Client Plan', help_text='Name of the default package assigned to each client account', max_length=80),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_storage_gb',
            field=models.PositiveIntegerField(default=5, help_text='Disk quota per client account (GB)'),
        ),
        migrations.AddField(
            model_name='resellerpackage',
            name='client_subdomains',
            field=models.PositiveIntegerField(default=5, help_text='Max subdomains per client'),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=80),
        ),
        migrations.AlterField(
            model_name='hostingpackage',
            name='package_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('wordpress', 'WordPress Hosting'), ('reseller', 'Reseller Hosting'), ('vps', 'Managed VPS'), ('marketing', 'Marketing Suite'), ('social', 'Social Media Suite'), ('email', 'Professional Email'), ('ssl', 'SSL Certificate'), ('domain', 'Domain Registration'), ('other', 'Other / Custom')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='resellerpackage',
            name='max_accounts',
            field=models.PositiveIntegerField(default=20, help_text='Max client accounts the reseller can host'),
        ),
        migrations.AlterField(
            model_name='resellerpackage',
            name='storage_gb',
            field=models.PositiveIntegerField(default=50, help_text='Total storage pool for this reseller (GB)'),
        ),
    ]
