# Generated by Django 6.0.3 on 2026-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_reseller_package_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingpackage',
            name='package_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('wordpress', 'WordPress Hosting'), ('reseller', 'Reseller Hosting'), ('marketing', 'Marketing Suite'), ('social', 'Social Media Suite'), ('email', 'Professional Email'), ('ssl', 'SSL Certificate'), ('domain', 'Domain Registration'), ('other', 'Other / Custom')], default='shared', max_length=30),
        ),
    ]
