# Generated by Django 6.0.3 on 2026-05-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_remove_vps_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='updates',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive versions are excluded from the migration path'),
        ),
        migrations.AddField(
            model_name='updates',
            name='is_breaking',
            field=models.BooleanField(default=False, help_text='If True, servers must not skip this version'),
        ),
        migrations.AddField(
            model_name='updates',
            name='min_version',
            field=models.CharField(blank=True, help_text='Minimum version required before this update can be applied (leave blank = any)', max_length=20),
        ),
        migrations.AddField(
            model_name='updates',
            name='notes',
            field=models.TextField(blank=True, help_text='What changed in this release'),
        ),
        migrations.AddField(
            model_name='updates',
            name='script_url',
            field=models.URLField(blank=True, help_text='URL to the updatepanel.sh for THIS version (e.g. https://voidpanel.com/updates/2.1.0/update.sh)'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='version',
            field=models.CharField(default=None, help_text='Semantic version, e.g. 2.1.0', max_length=20, unique=True),
        ),
    ]
