# Generated by Django 6.0.3 on 2026-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_emailorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_enabled', models.BooleanField(default=False)),
                ('facebook_app_id', models.CharField(blank=True, max_length=255)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=255)),
                ('instagram_enabled', models.BooleanField(default=False)),
                ('instagram_app_id', models.CharField(blank=True, max_length=255)),
                ('instagram_app_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_enabled', models.BooleanField(default=False)),
                ('twitter_api_key', models.CharField(blank=True, max_length=255)),
                ('twitter_api_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_bearer_token', models.CharField(blank=True, max_length=512)),
                ('linkedin_enabled', models.BooleanField(default=False)),
                ('linkedin_client_id', models.CharField(blank=True, max_length=255)),
                ('linkedin_client_secret', models.CharField(blank=True, max_length=255)),
                ('youtube_enabled', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, max_length=255)),
                ('google_client_secret', models.CharField(blank=True, max_length=255)),
                ('tiktok_enabled', models.BooleanField(default=False)),
                ('tiktok_client_key', models.CharField(blank=True, max_length=255)),
                ('tiktok_client_secret', models.CharField(blank=True, max_length=255)),
                ('pinterest_enabled', models.BooleanField(default=False)),
                ('pinterest_app_id', models.CharField(blank=True, max_length=255)),
                ('pinterest_app_secret', models.CharField(blank=True, max_length=255)),
                ('threads_enabled', models.BooleanField(default=False)),
                ('threads_app_id', models.CharField(blank=True, max_length=255)),
                ('threads_app_secret', models.CharField(blank=True, max_length=255)),
                ('gbusiness_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Platform Settings',
                'verbose_name_plural': 'Social Platform Settings',
            },
        ),
    ]
