# Generated by Django 6.0.4 on 2026-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_social_platform_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthRelayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_code', models.CharField(max_length=255, unique=True)),
                ('license_key', models.CharField(max_length=255)),
                ('token_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth Relay State',
                'verbose_name_plural': 'OAuth Relay States',
            },
        ),
    ]
