# Generated by Django 6.0.6 on 2026-07-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_hostingpricingsettings_signup_bonus_chips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingpricingsettings',
            name='signup_bonus_chips',
        ),
    ]
