# Generated by Django 5.2.1 on 2026-07-03 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_remove_hostingpricingsettings_signup_bonus_chips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='huggingface_api_key',
            field=models.CharField(blank=True, help_text='Hugging Face API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='huggingface_model',
            field=models.CharField(default='meta-llama/Meta-Llama-3-8B-Instruct', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='balance_chips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='balance_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='credits_per_rupee',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='signup_bonus_chips',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='active_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI ChatGPT'), ('huggingface', 'Hugging Face')], default='gemini', help_text='Which provider processes panel AI requests', max_length=20),
        ),
        migrations.CreateModel(
            name='ChipTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('grant', 'Grant'), ('purchase', 'Purchase'), ('adjustment', 'Admin Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Admin Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
