# Generated by Django 5.2.1 on 2026-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_aiproviderconfig_huggingface_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailorder',
            name='email_plan',
        ),
        migrations.RemoveField(
            model_name='emailservice',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='hostingpackage',
            name='server',
        ),
        migrations.RemoveField(
            model_name='hostingorder',
            name='package',
        ),
        migrations.RemoveField(
            model_name='marketingservice',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='resellerpackage',
            name='server',
        ),
        migrations.RemoveField(
            model_name='socialmediaservice',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='sslplan',
            name='server',
        ),
        migrations.RemoveField(
            model_name='sslservice',
            name='plan',
        ),
        migrations.AddField(
            model_name='emailorder',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emailservice',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostingorder',
            name='package_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='marketingservice',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='socialmediaservice',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sslservice',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='EmailPlan',
        ),
        migrations.DeleteModel(
            name='HostingPackage',
        ),
        migrations.DeleteModel(
            name='MarketingPlan',
        ),
        migrations.DeleteModel(
            name='ResellerPackage',
        ),
        migrations.DeleteModel(
            name='SocialMediaPlan',
        ),
        migrations.DeleteModel(
            name='SSLPlan',
        ),
    ]
