# Generated by Django 5.2.1 on 2026-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_remove_emailorder_email_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPackageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('ram_gb', models.IntegerField(blank=True, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('bandwidth_label', models.CharField(blank=True, max_length=100, null=True)),
                ('allowed_domains', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hosting package overrides',
            },
        ),
    ]
