# Generated by Django 5.2.1 on 2026-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_add_hosting_package_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryVoidPanelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='When disabled, the Try VoidPanel banner and page are hidden.')),
                ('headline', models.CharField(default='Try VoidPanel Free — No Credit Card Needed', help_text='Short headline shown on the Try VoidPanel page.', max_length=200)),
                ('sub_headline', models.CharField(blank=True, default='', help_text='Optional one-line sub-heading below the main headline.', max_length=400)),
                ('panel_url', models.CharField(blank=True, default='', help_text='Full URL of the demo panel, e.g. https://demo.voidpanel.com', max_length=500)),
                ('demo_username', models.CharField(blank=True, default='demo', help_text='Username shown to visitors for the demo panel login.', max_length=150)),
                ('demo_password', models.CharField(blank=True, default='', help_text='Password shown to visitors (store plain text — this is a demo account).', max_length=300)),
                ('server_ip', models.CharField(blank=True, default='', help_text='Optional: IP address displayed for SSH / additional info.', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note shown below the credentials (e.g. reset schedule, limitations).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Try VoidPanel Config',
                'verbose_name_plural': 'Try VoidPanel Config',
            },
        ),
    ]
