# Generated by Django 5.2.1 on 2026-07-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_add_try_voidpanel_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingpackageoverride',
            name='has_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingpackageoverride',
            name='has_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingpackageoverride',
            name='has_email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingpackageoverride',
            name='has_whatsapp_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
