# Generated by Django 5.2.1 on 2026-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_add_marketing_features_to_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='bandwidth_max_gb',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='bandwidth_min_gb',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='bandwidth_price_per_100gb',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='shared_max_databases',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='shared_max_emails',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hostingpricingsettings',
            name='shared_max_ftp',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
