# Generated by Django 5.2.1 on 2026-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_shared_hosting_pricing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPlanOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_mailboxes', models.IntegerField(blank=True, null=True)),
                ('storage_per_mailbox_gb', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email plan overrides',
            },
        ),
        migrations.CreateModel(
            name='SSLPlanOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('ssl_type', models.CharField(blank=True, max_length=20, null=True)),
                ('quarterly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_domains', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SSL plan overrides',
            },
        ),
    ]
