# Generated by Django 5.2.1 on 2026-07-03 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_email_ssl_plan_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_mailboxes', models.IntegerField(default=5)),
                ('storage_per_mailbox_gb', models.IntegerField(default=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='SSLPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('ssl_type', models.CharField(choices=[('dv', 'Domain Validated (DV)'), ('wildcard', 'Wildcard (*.domain.com)'), ('multi', 'Multi-Domain (SANs)')], default='dv', max_length=20)),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_domains', models.IntegerField(default=1)),
                ('validity_days', models.IntegerField(default=90)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SSL plans',
                'ordering': ['sort_order', 'quarterly_price'],
            },
        ),
    ]
