# Generated by Django 6.0.6 on 2026-07-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_email_ssl_full_plan_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='huggingface_model',
            field=models.CharField(default='meta-llama/Llama-3.1-8B-Instruct', max_length=150),
        ),
        migrations.CreateModel(
            name='SSLOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, default='', max_length=150)),
                ('domain', models.CharField(max_length=200)),
                ('billing_cycle', models.CharField(default='quarterly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('provision_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_order', to='data.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSL Order',
                'ordering': ['-created_at'],
            },
        ),
    ]
