# Generated by Django 6.0.6 on 2026-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_alter_aiproviderconfig_huggingface_model_sslorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidpanelserver',
            name='login_url',
            field=models.CharField(blank=True, default='', help_text='Global login URL for this server (e.g. https://panel.yourdomain.com:8443)', max_length=300),
        ),
    ]
