# Generated by Django 5.2.1 on 2026-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_voidpanelserver_login_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidpanelserver',
            name='nameservers',
            field=models.TextField(blank=True, default='ns1.voidpanel.com\nns2.voidpanel.com', help_text='Nameservers for this server, one per line'),
        ),
    ]
