# Generated by Django 5.2.15 on 2026-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_voidpanelserver_nameservers'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemailprofile',
            name='send_on_live_chat',
            field=models.BooleanField(default=True),
        ),
    ]
