# Generated by Django 5.2.15 on 2026-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_outboundemailprofile_send_on_live_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('content_html', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
