# Generated by Django 5.2.15 on 2026-07-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_suite_plans_services_orders'),
        ('data', '0053_globalemailtemplate'),
    ]

    operations = [
    ]
