# Generated by Django 5.2.15 on 2026-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_whatsappconfig_whatsapplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_annually',
            field=models.BooleanField(default=True, help_text='Applicable for annual/yearly billing cycle'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_monthly',
            field=models.BooleanField(default=True, help_text='Applicable for monthly billing cycle'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_quarterly',
            field=models.BooleanField(default=True, help_text='Applicable for quarterly billing cycle'),
        ),
    ]
