# Generated by Django 5.2.1 on 2026-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_coupon_applicable_annually_coupon_applicable_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingpackageoverride',
            name='has_seo_crm',
            field=models.BooleanField(default=True),
        ),
    ]
