# Generated by Django 5.2.1 on 2026-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_hostingpackageoverride_has_seo_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('purchase', 'Purchase / Order Confirmation'), ('invoice', 'Invoice'), ('suspend', 'Service Suspension'), ('welcome', 'Welcome / Onboarding'), ('live_chat', 'Live Chat Missed'), ('otp', 'OTP / Verification'), ('general', 'General')], default='general', max_length=40)),
                ('body', models.TextField(help_text='Message body. Use {{name}}, {{amount}}, {{service}}, etc. as placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='globalemailtemplate',
            name='category',
            field=models.CharField(choices=[('purchase', 'Purchase / Order Confirmation'), ('invoice', 'Invoice'), ('suspend', 'Service Suspension'), ('welcome', 'Welcome / Onboarding'), ('live_chat', 'Live Chat'), ('password', 'Password Reset'), ('general', 'General')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='globalemailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
