# Generated by Django 5.2.1 on 2026-07-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_license_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='panellicenserecord',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter — Free'), ('pro', 'Pro — ₹999/mo'), ('advanced', 'Advanced — ₹2,499/mo'), ('unlimited', 'Unlimited — ₹4,999/mo')], default='pro', help_text='License tier determines which features are available', max_length=20),
        ),
        migrations.CreateModel(
            name='ErpCrmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('package_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('subdomain', models.CharField(max_length=64)),
                ('admin_name', models.CharField(max_length=120)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=128)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_order', to='data.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP/CRM Order',
                'verbose_name_plural': 'ERP/CRM Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErpCrmService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('subdomain', models.CharField(max_length=64, unique=True)),
                ('package_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('dashboard_url', models.URLField(blank=True, max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP/CRM Service',
                'verbose_name_plural': 'ERP/CRM Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
