# Generated by Django 5.2.1 on 2026-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_alter_panellicenserecord_tier_erpcrmorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpcrmservice',
            name='custom_domain',
            field=models.CharField(blank=True, default='', help_text='Optional custom domain, e.g. hr.mycompany.com', max_length=255),
        ),
    ]
