# Generated by Django 5.2.1 on 2026-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_erp_service_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpcrmorder',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
