# Generated by Django 5.2.1 on 2026-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_erp_order_custom_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLDPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(help_text='e.g. .com, .in, .co.in', max_length=30, unique=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, help_text='Cost price in INR from ConnectReseller', max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, help_text='Selling price in INR (wholesale + margin)', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this TLD on the domain search page')),
            ],
            options={
                'verbose_name': 'TLD Price',
                'verbose_name_plural': 'TLD Prices',
                'ordering': ['retail_price'],
            },
        ),
        migrations.AlterModelOptions(
            name='domainorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='connectresellerconfig',
            name='auto_provision_after_payment',
            field=models.BooleanField(default=False, help_text='If ON, domains are automatically purchased from ConnectReseller after payment. If OFF, admin must manually provision.'),
        ),
        migrations.AddField(
            model_name='connectresellerconfig',
            name='last_price_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectresellerconfig',
            name='price_sync_log',
            field=models.TextField(blank=True, default='', help_text='Log output from last price sync'),
        ),
        migrations.AddField(
            model_name='connectresellerconfig',
            name='price_sync_status',
            field=models.CharField(choices=[('never', 'Never'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='provision_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='provision_status',
            field=models.CharField(choices=[('not_provisioned', 'Not Provisioned'), ('db_activated', 'Activated in DB'), ('api_provisioned', 'Provisioned via API'), ('failed', 'Provision Failed')], default='not_provisioned', max_length=20),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
