# Generated by Django 5.2.1 on 2026-07-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_tldprice_alter_domainorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPortalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('package_name', models.CharField(max_length=50)),
                ('gym_name', models.CharField(max_length=150)),
                ('owner_username', models.CharField(max_length=80)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_password', models.CharField(max_length=128)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_order', to='data.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Portal Order',
                'verbose_name_plural': 'Gym Portal Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymPortalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=150)),
                ('owner_username', models.CharField(max_length=80)),
                ('package_name', models.CharField(max_length=50)),
                ('package_id', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('dashboard_url', models.URLField(blank=True, default='https://gym.voidonyx.in', max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('max_clients', models.IntegerField(default=50)),
                ('max_trainers', models.IntegerField(default=5)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('remote_gym_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Portal Service',
                'verbose_name_plural': 'Gym Portal Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
