# Generated by Django 5.2.1 on 2026-07-31 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_aivoiceorder_aivoiceservice_hotelportalorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatabookorder',
            name='package_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='khatabookservice',
            name='package_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='khatabookservice',
            name='remote_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='LeadGenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=64)),
                ('package_name', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=150)),
                ('owner_username', models.CharField(max_length=80)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_password', models.CharField(max_length=128)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadgen_order', to='data.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadgen_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Generator Order',
                'verbose_name_plural': 'Lead Generator Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadGenService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('owner_username', models.CharField(max_length=80)),
                ('package_name', models.CharField(max_length=50)),
                ('package_id', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('dashboard_url', models.URLField(blank=True, default='https://leads.voidonyx.in', max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('max_leads', models.IntegerField(default=500, help_text='Max leads allowed')),
                ('max_members', models.IntegerField(default=3, help_text='Max team members')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('remote_id', models.CharField(blank=True, max_length=64, null=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadgen_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Generator Service',
                'verbose_name_plural': 'Lead Generator Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
