# Generated by Django 5.2.15 on 2026-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_alter_khatabookorder_package_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatabookservice',
            name='remote_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
