# Generated by Django 5.2.15 on 2026-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_alter_khatabookservice_remote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('identity', models.CharField(blank=True, db_index=True, help_text='The email/username attempted', max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('succeeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='data_logina_ip_addr_69daf1_idx'), models.Index(fields=['identity', 'created_at'], name='data_logina_identit_259bf9_idx')],
            },
        ),
    ]
