# Generated by Django 5.2.15 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatabookorder',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
