"""
Django settings for panel project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os as _os

# Load SECRET_KEY from environment; fall back to file; generate fresh key as last resort.
def _load_secret_key():
    _env_key = _os.environ.get('DJANGO_SECRET_KEY', '').strip()
    if _env_key:
        return _env_key
    _key_file = _os.path.join(_os.path.dirname(_os.path.dirname(__file__)), '.secret_key')
    if _os.path.exists(_key_file):
        with open(_key_file, 'r') as _f:
            _stored = _f.read().strip()
        if _stored:
            return _stored
    from django.core.management.utils import get_random_secret_key
    _fresh = get_random_secret_key()
    try:
        with open(_key_file, 'w') as _f:
            _f.write(_fresh)
        _os.chmod(_key_file, 0o600)
    except Exception:
        pass
    return _fresh

SECRET_KEY = _load_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _os.environ.get('DJANGO_DEBUG', '').strip().lower() in ('1', 'true', 'yes')

# Accept the server's own hostname/IP; '*' is replaced by the actual host at setup time.
# Additional hostnames are appended by change_hostname() at install time.
# Operators can restrict this via DJANGO_ALLOWED_HOSTS env var (comma-separated).
_hosts_env = _os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts_env.split(',') if h.strip()] if _hosts_env else ['*']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
    'control',
    'chatting',
    'channels',
]
# Allow iframes only from same origin (needed for file manager, terminal embeds)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ── Cookie & transport security ───────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True   # JS cannot read session cookie
CSRF_COOKIE_HTTPONLY    = False  # Django needs JS to read CSRF cookie (for AJAX)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE    = 'Lax'
# Set SECURE cookies only when not in debug mode AND running over HTTPS
_HTTPS_ENABLED = _os.environ.get('VOIDPANEL_HTTPS', '').strip().lower() in ('1', 'true', 'yes')
if not DEBUG:
    SESSION_COOKIE_SECURE = _HTTPS_ENABLED
    CSRF_COOKIE_SECURE    = _HTTPS_ENABLED

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'panel.wsgi.application'
ASGI_APPLICATION = 'panel.asgi.application'

try:
    import channels_redis  # noqa: F401 — verify it is installed
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [('127.0.0.1', 6379)],
            },
        },
    }
except ImportError:
    # Fall back to in-memory layer during initial install (before pip install completes)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes

# Maximum size of file upload handlers in memory before writing to disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes

# Adjust the number of fields Django can handle for large form submissions if needed
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000 

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'



STATIC_ROOT = _os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# CSRF trusted origins — populated dynamically by change_hostname() at install.
# Operators can override via DJANGO_CSRF_ORIGINS env var (comma-separated).
_csrf_env = _os.environ.get('DJANGO_CSRF_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(',') if o.strip()] if _csrf_env else []

# Critical for HTTPS proxying (e.g. Nginx on port 8082 proxying to 8080) to pass CSRF validation
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional: Additional static file storage settings
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# {% load static %}
# <img src="{% static 'images/logo.png' %}" alt="Logo">
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 86400
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ─────────────────────────────────────────────────────────────
# Celery — async task queue
# Install: pip install celery redis
# Start worker: celery -A panel worker --loglevel=info
# ─────────────────────────────────────────────────────────────
CELERY_BROKER_URL          = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND      = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT      = ['json']
CELERY_TASK_SERIALIZER     = 'json'
CELERY_RESULT_SERIALIZER   = 'json'
CELERY_TIMEZONE            = TIME_ZONE
CELERY_TASK_TRACK_STARTED  = True   # tasks show STARTED state in Flower
CELERY_TASK_ACKS_LATE      = True   # don't ack until task finishes (crash-safe)

# ─────────────────────────────────────────────────────────────
# Django logging — routes voidpanel.* to /var/log/voidpanel/
# (panel/logger.py sets up the actual handlers at import time)
# ─────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'voidpanel': {
            'format': '%(asctime)s [%(levelname)s] %(name)s — %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'voidpanel',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        # VoidPanel custom namespace — panel/logger.py adds rotating file handlers
        'voidpanel': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
