# Generated by Django 5.1 on 2024-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('nameserver1', models.CharField(max_length=255)),
                ('nameserver2', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
