# Generated by Django 5.1 on 2024-08-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick',
            name='email',
            field=models.EmailField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='quick',
            name='hostname',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='quick',
            name='nameserver1',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='quick',
            name='nameserver2',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
