# Generated by Django 5.1 on 2024-08-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_quick_email_alter_quick_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
