# Generated by Django 5.1 on 2024-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_quick_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
