# Generated by Django 5.1 on 2024-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_quick_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=150)),
                ('successful', models.BooleanField(default=True, help_text='Whether the login attempt was successful')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('storage', models.TextField(help_text='Storage in GB')),
                ('ftp', models.TextField(help_text='Storage in GB')),
                ('subdomain', models.TextField(help_text='Storage in GB')),
                ('bandwidth', models.TextField(help_text='Bandwidth in GB')),
                ('domains_allowed', models.TextField(help_text='Number of domains allowed')),
                ('email_accounts', models.TextField(help_text='Number of email accounts allowed')),
                ('databases_allowed', models.TextField(help_text='Number of databases allowed')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=150)),
                ('hosting_package', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
