# Generated by Django 5.1.1 on 2024-09-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_loginactivity_package_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
