# Generated by Django 5.1.1 on 2024-09-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dir',
            field=models.CharField(default=34, max_length=255),
            preserve_default=False,
        ),
    ]
