# Generated by Django 5.1.1 on 2024-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_domain_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='allemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
    ]
