# Generated by Django 5.1.1 on 2024-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_cron'),
    ]

    operations = [
        migrations.CreateModel(
            name='subdomainname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
