# Generated by Django 5.1.1 on 2024-09-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_subdomainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='sslstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomainname',
            name='sslstatus',
            field=models.BooleanField(default=False),
        ),
    ]
