# Generated by Django 5.1.1 on 2024-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_domain_sslstatus_subdomainname_sslstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='php',
            field=models.CharField(default='8.3', max_length=10),
        ),
    ]
