# Generated by Django 5.1.1 on 2024-09-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_phpversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainname',
            name='php',
            field=models.CharField(default='8.3', max_length=10),
        ),
    ]
