# Generated by Django 5.1.1 on 2024-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_subdomainname_php'),
    ]

    operations = [
        migrations.CreateModel(
            name='redir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('newpath', models.CharField(max_length=255)),
            ],
        ),
    ]
