# Generated by Django 5.1.1 on 2024-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_redir'),
    ]

    operations = [
        migrations.AddField(
            model_name='redir',
            name='maindomain',
            field=models.CharField(default=34, max_length=100),
            preserve_default=False,
        ),
    ]
