# Generated by Django 5.1.1 on 2024-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_redir_maindomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
