# Generated by Django 5.1.1 on 2024-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_domain_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
