# Generated by Django 5.1.1 on 2024-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_firewall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
