# Generated by Django 5.1.1 on 2024-10-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_ftp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='shell',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
