# Generated by Django 5.1.1 on 2024-10-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_rename_is_staff_user_shell_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
