# Generated by Django 5.1.1 on 2024-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='userdomain',
            field=models.BooleanField(default=False),
        ),
    ]
