# Generated by Django 5.1.1 on 2024-10-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftpaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('storage', models.CharField(max_length=150)),
            ],
        ),
    ]
