# Generated by Django 5.1.1 on 2024-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_ftpaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpaccount',
            name='main',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
