# Generated by Django 5.1.1 on 2024-10-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_ftpaccount_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='domains_allowed',
        ),
    ]
