# Generated by Django 5.1.2 on 2024-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_pythonname'),
    ]

    operations = [
        migrations.CreateModel(
            name='portnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
