# Generated by Django 5.1.2 on 2024-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_portnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonname',
            name='main',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
