# Generated by Django 5.1.2 on 2024-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_pythonname_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='phpextentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('extentions', models.TextField(default=None)),
            ],
        ),
    ]
