# Generated by Django 5.1.2 on 2024-12-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_phpextentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='mernname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('main', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
