# Generated by Django 5.1.2 on 2025-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_mernname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mernname',
            name='port',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
