# Generated by Django 6.0.3 on 2026-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_mernname_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_limit', models.IntegerField(default=100, help_text='Max outgoing emails per hour')),
                ('daily_limit', models.IntegerField(default=1000, help_text='Max outgoing emails per day')),
                ('default_quota_mb', models.IntegerField(default=1024, help_text='Max MB per inbox')),
                ('max_attachment_size_mb', models.IntegerField(default=50, help_text='Max attachment size in MB')),
                ('enable_antispam', models.BooleanField(default=True, help_text='Enable SpamAssassin checks')),
                ('spam_score_threshold', models.FloatField(default=5.0, help_text='Score before rejection')),
                ('enforce_dkim_spf', models.BooleanField(default=True, help_text='Reject emails failing DKIM/SPF')),
                ('max_concurrent_connections', models.IntegerField(default=20, help_text='SMTP concurrent limits')),
                ('catch_all_capability', models.BooleanField(default=False, help_text='Allow wildcard aliases')),
                ('allow_autoresponders', models.BooleanField(default=True, help_text='Allow vacation replies')),
            ],
        ),
    ]
