# Generated by Django 6.0.3 on 2026-04-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpaccount',
            name='main',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mernname',
            name='main',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mernname',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
