# Generated by Django 6.0.3 on 2026-04-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_panellicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('domain', 'Domain'), ('python', 'Python App'), ('mern', 'MERN Stack'), ('email', 'Email'), ('db', 'Database'), ('ssl', 'SSL'), ('ftp', 'FTP'), ('system', 'System'), ('nginx', 'Nginx'), ('backup', 'Backup')], default='system', max_length=15)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain', '-timestamp'], name='control_act_domain_f957ca_idx'), models.Index(fields=['level', '-timestamp'], name='control_act_level_0b9ac8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=120)),
                ('branding_name', models.CharField(blank=True, default='VoidPanel', help_text='Name shown to reseller in their dashboard', max_length=60)),
                ('storage_quota_gb', models.PositiveIntegerField(default=10, help_text='Total GB of disk space this reseller can allocate across ALL sub-accounts')),
                ('max_accounts', models.PositiveIntegerField(default=5, help_text='Maximum number of hosting sub-accounts this reseller can create')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(help_text='Django auth user that logs in as reseller', on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Profile',
                'verbose_name_plural': 'Reseller Profiles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text="If set, this account belongs to this reseller's pool", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='control.resellerprofile'),
        ),
    ]
