# Generated by Django 6.0.3 on 2026-04-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_cloud_backup_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='The main domain this belongs to', max_length=255)),
                ('username', models.CharField(help_text='System user (dir) who owns this install', max_length=150)),
                ('script_name', models.CharField(help_text="e.g. 'wordpress', 'ghost', 'nextcloud'", max_length=100)),
                ('install_url', models.CharField(help_text='The URL where the script is installed (domain or subdomain)', max_length=255)),
                ('install_dir', models.CharField(blank=True, help_text='Filesystem path, e.g. /home/user/public_html', max_length=512)),
                ('admin_user', models.CharField(blank=True, max_length=150)),
                ('admin_email', models.CharField(blank=True, max_length=255)),
                ('admin_url', models.CharField(blank=True, help_text='e.g. https://domain.com/wp-admin', max_length=512)),
                ('db_name', models.CharField(blank=True, max_length=100)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('installing', 'Installing'), ('active', 'Active'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='installing', max_length=20)),
                ('log', models.TextField(blank=True, default='', help_text='Installation log / error output')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Installed Script',
                'verbose_name_plural': 'Installed Scripts',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.AlterField(
            model_name='cloudbackupconfig',
            name='auto_schedule_cron',
            field=models.CharField(blank=True, default='0 2 * * *', help_text='Cron string (used when preset=custom)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cloudbackupconfig',
            name='gcs_key_json',
            field=models.TextField(blank=True, help_text='Service Account JSON key (paste full contents)'),
        ),
        migrations.AlterField(
            model_name='cloudbackupconfig',
            name='sync_after_backup',
            field=models.BooleanField(default=False, help_text='Auto-push to cloud immediately after each backup'),
        ),
        migrations.CreateModel(
            name='ResellerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package display name', max_length=100)),
                ('storage_gb', models.PositiveIntegerField(default=1, help_text='Disk quota in GB')),
                ('bandwidth_gb', models.PositiveIntegerField(default=10, help_text='Monthly bandwidth in GB')),
                ('email_accounts', models.PositiveIntegerField(default=5, help_text='Max email accounts')),
                ('databases', models.PositiveIntegerField(default=2, help_text='Max databases')),
                ('subdomains', models.PositiveIntegerField(default=5, help_text='Max subdomains')),
                ('ftp_accounts', models.PositiveIntegerField(default=2, help_text='Max FTP accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(help_text='Reseller who owns this package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='control.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Package',
                'verbose_name_plural': 'Reseller Packages',
                'ordering': ['name'],
                'unique_together': {('reseller', 'name')},
            },
        ),
    ]
