# Generated by Django 5.2.13 on 2026-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedscript',
            name='db_pass',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='scopes',
            field=models.JSONField(default=list, help_text='List of allowed scope strings e.g. ["accounts.list","dns.create"]'),
        ),
    ]
