# Generated by Django 6.0.3 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0043_installedscript_db_pass_alter_apitoken_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('fb', 'Facebook'), ('ig', 'Instagram'), ('tw', 'Twitter / X'), ('li', 'LinkedIn'), ('pi', 'Pinterest'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('th', 'Threads'), ('gb', 'Google Business')], max_length=4)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_username', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('following_count', models.BigIntegerField(default=0)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, max_length=255)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['platform', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_app_id', models.CharField(blank=True, max_length=255)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=255)),
                ('instagram_app_id', models.CharField(blank=True, max_length=255)),
                ('instagram_app_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_api_key', models.CharField(blank=True, max_length=255)),
                ('twitter_api_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_bearer_token', models.CharField(blank=True, max_length=512)),
                ('linkedin_client_id', models.CharField(blank=True, max_length=255)),
                ('linkedin_client_secret', models.CharField(blank=True, max_length=255)),
                ('pinterest_app_id', models.CharField(blank=True, max_length=255)),
                ('pinterest_app_secret', models.CharField(blank=True, max_length=255)),
                ('tiktok_client_key', models.CharField(blank=True, max_length=255)),
                ('tiktok_client_secret', models.CharField(blank=True, max_length=255)),
                ('google_client_id', models.CharField(blank=True, max_length=255)),
                ('google_client_secret', models.CharField(blank=True, max_length=255)),
                ('threads_app_id', models.CharField(blank=True, max_length=255)),
                ('threads_app_secret', models.CharField(blank=True, max_length=255)),
                ('enabled_platforms', models.JSONField(default=list, help_text='List of enabled platform codes e.g. ["fb","ig","tw"]')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media API Config',
                'verbose_name_plural': 'Social Media API Config',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('caption_text', models.TextField(blank=True)),
                ('first_comment', models.TextField(blank=True, help_text='First comment (hashtag trick)')),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('link_url', models.URLField(blank=True)),
                ('link_title', models.CharField(blank=True, max_length=255)),
                ('link_description', models.TextField(blank=True)),
                ('link_thumbnail', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_ids', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=50)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('reach_count', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('impressions_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='posts', to='control.socialaccount')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
