# Generated by Django 6.0.6 on 2026-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0045_marketingabtest_marketingcampaign_marketinglead'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
