# Generated by Django 6.0.6 on 2026-06-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0047_campaignrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('msg91', 'MSG91'), ('vonage', 'Vonage (Nexmo)'), ('textlocal', 'TextLocal'), ('plivo', 'Plivo'), ('aws_sns', 'AWS SNS')], max_length=20)),
                ('api_key', models.CharField(help_text='API Key / Account SID', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='API Secret / Auth Token', max_length=255)),
                ('sender_id', models.CharField(blank=True, help_text='Sender ID or Phone Number (e.g. +1234567890)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'domain', 'provider')},
            },
        ),
    ]
