# Generated by Django 6.0.6 on 2026-06-25 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0048_smsgatewayconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('label', models.CharField(help_text='Display name, e.g. "My Gmail"', max_length=100)),
                ('from_email', models.EmailField(help_text='From address shown to recipients', max_length=254)),
                ('smtp_host', models.CharField(help_text='e.g. smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(help_text='SMTP login username', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP login password or app password', max_length=255)),
                ('encryption', models.CharField(choices=[('tls', 'TLS (587)'), ('ssl', 'SSL (465)'), ('none', 'None (25)')], default='tls', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_smtp_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
