# Generated by Django 6.0.6 on 2026-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0049_customsmtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='enable_smtp_relay',
            field=models.BooleanField(default=False, help_text='Enable system-wide Postfix SMTP Relay'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='smtp_relay_host',
            field=models.CharField(default='[smtp.sendgrid.net]:587', help_text='SMTP Relay Host, e.g., [smtp.sendgrid.net]:587', max_length=255),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='smtp_relay_password',
            field=models.CharField(blank=True, default='', help_text='SMTP Relay Password/API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='smtp_relay_username',
            field=models.CharField(blank=True, default='', help_text='SMTP Relay Username', max_length=255),
        ),
    ]
