# Generated by Django 6.0.6 on 2026-06-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0050_emailconfig_enable_smtp_relay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('ports', models.JSONField(blank=True, default=dict)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('volumes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
