# Generated by Django 6.0.6 on 2026-06-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0051_dockercontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('api_token', models.CharField(max_length=255)),
                ('zone_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
