# Generated by Django 6.0.6 on 2026-07-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0052_cloudflareintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='custom_smtp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='control.customsmtpconfig'),
        ),
    ]
