# Generated by Django 6.0.6 on 2026-07-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0053_marketingcampaign_custom_smtp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('auto', 'Auto Update (midnight)'), ('manual', 'Manual Update')], default='auto', max_length=10)),
                ('last_auto_update', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Update Settings',
                'verbose_name_plural': 'Update Settings',
            },
        ),
        migrations.CreateModel(
            name='AIChipBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField(default=20, help_text='Remaining AI chips. 0 = blocked.')),
                ('last_refilled', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chip_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chip Balance',
                'verbose_name_plural': 'AI Chip Balances',
            },
        ),
        migrations.CreateModel(
            name='AIChipTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Negative = deduction, Positive = top-up')),
                ('description', models.CharField(default='AI command', max_length=255)),
                ('balance_after', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chip_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chip Transaction',
                'verbose_name_plural': 'AI Chip Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
