# Generated by Django 5.2.15 on 2026-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0054_updatesettings_aichipbalance_aichiptransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_smtp_verified', models.BooleanField(default=False)),
                ('notify_user_created', models.BooleanField(default=False)),
                ('notify_ssl_generated', models.BooleanField(default=False)),
                ('notify_login_alert', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
