# Generated by Django 5.2.15 on 2026-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0056_expand_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflareintegration',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
