# Generated by Django 5.2.15 on 2026-07-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0057_cloudflareintegration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainer',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
