# Generated by Django 6.0.6 on 2026-07-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0059_marketingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('last_message', models.TextField(blank=True, default='')),
                ('last_ts', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('domain', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='WaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='out', max_length=3)),
                ('message_id', models.CharField(blank=True, default='', max_length=100)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='control.waconversation')),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['domain', 'phone', 'ts'], name='control_wam_domain_fd883e_idx')],
            },
        ),
    ]
