# Generated by Django 6.0.6 on 2026-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0060_waconversation_wamessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='wa_media_path',
            field=models.CharField(blank=True, default='', help_text='Server-side path to attached media file (image/video/doc)', max_length=500),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='wa_media_type',
            field=models.CharField(blank=True, default='', help_text='MIME type, e.g. image/jpeg, video/mp4, application/pdf', max_length=20),
        ),
    ]
