# Generated by Django 6.0.6 on 2026-07-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0061_marketingcampaign_wa_media_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(default='contact_created', max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('action_type', models.CharField(max_length=20)),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('template_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message_text', models.TextField(blank=True, default='')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='control.marketingworkflow')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkflowEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='control.marketinglead')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='control.marketingworkflow')),
            ],
            options={
                'unique_together': {('workflow', 'lead')},
            },
        ),
    ]
