# Generated by Django 5.2.1 on 2026-07-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0065_panellicense_tier_features_panelbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSocialAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('facebook_app_id', models.CharField(blank=True, max_length=255)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_api_key', models.CharField(blank=True, max_length=255)),
                ('twitter_api_secret', models.CharField(blank=True, max_length=255)),
                ('twitter_bearer_token', models.CharField(blank=True, max_length=512)),
                ('twitter_access_token', models.CharField(blank=True, max_length=512)),
                ('twitter_access_secret', models.CharField(blank=True, max_length=512)),
                ('linkedin_client_id', models.CharField(blank=True, max_length=255)),
                ('linkedin_client_secret', models.CharField(blank=True, max_length=255)),
                ('pinterest_app_id', models.CharField(blank=True, max_length=255)),
                ('pinterest_app_secret', models.CharField(blank=True, max_length=255)),
                ('tiktok_client_key', models.CharField(blank=True, max_length=255)),
                ('tiktok_client_secret', models.CharField(blank=True, max_length=255)),
                ('google_client_id', models.CharField(blank=True, max_length=255)),
                ('google_client_secret', models.CharField(blank=True, max_length=255)),
                ('redirect_uri', models.URLField(blank=True, help_text='Your OAuth callback URL — copy from your developer app settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain Social API Config',
                'verbose_name_plural': 'Domain Social API Configs',
            },
        ),
        migrations.RemoveIndex(
            model_name='wamessage',
            name='control_wam_domain_fd883e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='waconversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='waconversation',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wamessage',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='panelbranding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suiteplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suiteplan',
            name='suite',
            field=models.CharField(choices=[('social', 'Social Media Suite'), ('seo', 'SEO Suite'), ('marketing', 'Marketing Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suitessotoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suitessotoken',
            name='suite',
            field=models.CharField(choices=[('social', 'Social Media Suite'), ('seo', 'SEO Suite'), ('marketing', 'Marketing Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suitesubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suitesubscription',
            name='suite',
            field=models.CharField(choices=[('social', 'Social Media Suite'), ('seo', 'SEO Suite'), ('marketing', 'Marketing Suite')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='waconversation',
            unique_together={('domain', 'username', 'phone')},
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['domain', 'username', 'phone', 'ts'], name='control_wam_domain_3a1657_idx'),
        ),
    ]
