# Generated by Django 5.2.1 on 2026-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0066_domainsocialapiconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitesubscription',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='suitesubscription',
            unique_together={('email', 'suite')},
        ),
    ]
